//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuaSTGEditorSharpV2.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localized {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LuaSTGEditorSharpV2.Resources.Localized", typeof(Localized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 LuaSTG Editor Sharp V2 Document(*.lstgxml;*.lstgjson)|*.lstgxml;*.lstgjson 的本地化字符串。
        /// </summary>
        internal static string openFileCommandDialog_fileExtension {
            get {
                return ResourceManager.GetString("openFileCommandDialog_fileExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Document 的本地化字符串。
        /// </summary>
        internal static string ribbon_backStageMenu_document_title {
            get {
                return ResourceManager.GetString("ribbon_backStageMenu_document_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Child 的本地化字符串。
        /// </summary>
        internal static string ribbon_button_childDirection_title {
            get {
                return ResourceManager.GetString("ribbon_button_childDirection_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code Export 的本地化字符串。
        /// </summary>
        internal static string ribbon_button_code_title {
            get {
                return ResourceManager.GetString("ribbon_button_code_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Copy 的本地化字符串。
        /// </summary>
        internal static string ribbon_button_copy_title {
            get {
                return ResourceManager.GetString("ribbon_button_copy_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cut 的本地化字符串。
        /// </summary>
        internal static string ribbon_button_cut_title {
            get {
                return ResourceManager.GetString("ribbon_button_cut_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Down 的本地化字符串。
        /// </summary>
        internal static string ribbon_button_downDirection_title {
            get {
                return ResourceManager.GetString("ribbon_button_downDirection_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Jump to... 的本地化字符串。
        /// </summary>
        internal static string ribbon_button_jumpTo_title {
            get {
                return ResourceManager.GetString("ribbon_button_jumpTo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parent 的本地化字符串。
        /// </summary>
        internal static string ribbon_button_parentDirection_title {
            get {
                return ResourceManager.GetString("ribbon_button_parentDirection_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Paste 的本地化字符串。
        /// </summary>
        internal static string ribbon_button_paste_title {
            get {
                return ResourceManager.GetString("ribbon_button_paste_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Up 的本地化字符串。
        /// </summary>
        internal static string ribbon_button_upDirection_title {
            get {
                return ResourceManager.GetString("ribbon_button_upDirection_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Code Export 的本地化字符串。
        /// </summary>
        internal static string ribbon_group_code_title {
            get {
                return ResourceManager.GetString("ribbon_group_code_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Edit 的本地化字符串。
        /// </summary>
        internal static string ribbon_group_edit_title {
            get {
                return ResourceManager.GetString("ribbon_group_edit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insert Direction 的本地化字符串。
        /// </summary>
        internal static string ribbon_group_insertDirection_title {
            get {
                return ResourceManager.GetString("ribbon_group_insertDirection_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Navigation 的本地化字符串。
        /// </summary>
        internal static string ribbon_group_navigation_title {
            get {
                return ResourceManager.GetString("ribbon_group_navigation_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Exit 的本地化字符串。
        /// </summary>
        internal static string ribbon_menuItem_exit_title {
            get {
                return ResourceManager.GetString("ribbon_menuItem_exit_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Export code... 的本地化字符串。
        /// </summary>
        internal static string ribbon_menuItem_exportCode_title {
            get {
                return ResourceManager.GetString("ribbon_menuItem_exportCode_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Open... 的本地化字符串。
        /// </summary>
        internal static string ribbon_menuItem_open_title {
            get {
                return ResourceManager.GetString("ribbon_menuItem_open_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string ribbon_menuItem_save_title {
            get {
                return ResourceManager.GetString("ribbon_menuItem_save_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save As... 的本地化字符串。
        /// </summary>
        internal static string ribbon_menuItem_saveAs_title {
            get {
                return ResourceManager.GetString("ribbon_menuItem_saveAs_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Settings 的本地化字符串。
        /// </summary>
        internal static string ribbon_menuItem_settings_title {
            get {
                return ResourceManager.GetString("ribbon_menuItem_settings_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 View code... 的本地化字符串。
        /// </summary>
        internal static string ribbon_menuItem_viewCode_title {
            get {
                return ResourceManager.GetString("ribbon_menuItem_viewCode_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Redo 的本地化字符串。
        /// </summary>
        internal static string ribbon_quickAccess_redo_title {
            get {
                return ResourceManager.GetString("ribbon_quickAccess_redo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Save 的本地化字符串。
        /// </summary>
        internal static string ribbon_quickAccess_save_title {
            get {
                return ResourceManager.GetString("ribbon_quickAccess_save_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Undo 的本地化字符串。
        /// </summary>
        internal static string ribbon_quickAccess_undo_title {
            get {
                return ResourceManager.GetString("ribbon_quickAccess_undo_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Home 的本地化字符串。
        /// </summary>
        internal static string ribbon_tab_home_title {
            get {
                return ResourceManager.GetString("ribbon_tab_home_title", resourceCulture);
            }
        }
    }
}
