using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

using LuaSTGEditorSharpV2.Core;
using LuaSTGEditorSharpV2.Core.Command;
using LuaSTGEditorSharpV2.Core.Model;
using LuaSTGEditorSharpV2.ViewModel;

namespace LuaSTGEditorSharpV2.PropertyView
{
    // TODO: re-design "subtype". maybe it should be supported individually for each property.
    /// <summary>
    /// Provide functionality of presenting and manipulating <see cref="NodeData"/> properties.
    /// </summary>
    [ServiceName("PropertyView"), ServiceShortName("prop")]
    public class PropertyViewServiceBase 
        : NodeService<PropertyViewServiceBase, PropertyViewContext, PropertyViewServiceSettings>
    {
        private static readonly PropertyViewServiceBase _defaultService = new();

        private static readonly List<string> _resourceDictUris = new();

        public static IReadOnlyList<string> ResourceDictUris => _resourceDictUris;

        static PropertyViewServiceBase()
        {
            _defaultServiceGetter = () => _defaultService;
        }

        public static IReadOnlyList<PropertyViewModel> GetPropertyViewModelOfNode(NodeData nodeData
            , LocalServiceParam localParam, int subtype = 0)
            => GetPropertyViewModelOfNode(nodeData, localParam, ServiceSettings, subtype);

        /// <summary>
        /// Obtain a list of <see cref="PropertyViewModel"/> according to data source for providing properties to edit. 
        /// </summary>
        /// <param name="nodeData"> The data source. </param>
        /// <param name="localParam"> Th local param for this action. </param>
        /// <param name="serviceSettings"> The <see cref="PropertyViewServiceSettings"/> for this action. </param>
        /// <param name="subtype"></param>
        /// <returns></returns>
        public static IReadOnlyList<PropertyViewModel> GetPropertyViewModelOfNode(NodeData nodeData
            , LocalServiceParam localParam, PropertyViewServiceSettings serviceSettings, int subtype = 0)
        {
            var ctx = GetContextOfNode(nodeData, localParam, serviceSettings);
            return GetServiceOfNode(nodeData).ResolvePropertyViewModelOfNode(nodeData, ctx, subtype);
        }

        public static CommandBase GetCommandOfEditingNode(NodeData nodeData
            , IReadOnlyList<PropertyViewModel> propertyList, LocalServiceParam localParams
            , int index, string edited, int subtype = 0)
            => GetCommandOfEditingNode(nodeData, propertyList, localParams, ServiceSettings
                , index, edited, subtype);

        /// <summary>
        /// Obtain a command which manipulate target <see cref="NodeData"/> by infomation from UI.
        /// </summary>
        /// <param name="nodeData"> The data source. </param>
        /// <param name="propertyList"> 
        /// The <see cref="PropertyViewModel"/> generated by <see cref="GetPropertyViewModelOfNode"/>. 
        /// </param>
        /// <param name="localParams"> The local params for executing the service. </param>
        /// <param name="index"> Index of item in <see cref="PropertyViewModel"/>s. </param>
        /// <param name="edited"> The <see cref="string"/> as edit result. </param>
        /// <param name="subtype"></param>
        /// <returns></returns>
        public static CommandBase GetCommandOfEditingNode(NodeData nodeData
            , IReadOnlyList<PropertyViewModel> propertyList, LocalServiceParam localParams
            , PropertyViewServiceSettings serviceSettings, int index, string edited, int subtype = 0)
        {
            return GetServiceOfNode(nodeData).ResolveCommandOfEditingNode(nodeData, propertyList
                , GetContextOfNode(nodeData, localParams, serviceSettings), index, edited, subtype);
        }

        public static void AddResourceDictUri(string uri)
        {
            _resourceDictUris.Add(uri);
        }

        public override sealed PropertyViewContext GetEmptyContext(LocalServiceParam localSettings
            , PropertyViewServiceSettings serviceSettings)
        {
            return new PropertyViewContext(localSettings, serviceSettings);
        }

        /// <summary>
        /// Obtain a list of <see cref="PropertyViewModel"/> according to data source with 
        /// same TypeUID for providing properties to edit.
        /// </summary>
        /// <param name="nodeData"> The data source with the same TypeUID. </param>
        /// <param name="subtype"></param>
        /// <returns></returns>
        protected virtual IReadOnlyList<PropertyViewModel> ResolvePropertyViewModelOfNode(NodeData nodeData
            , PropertyViewContext context, int subtype = 0)
        {
            List<PropertyViewModel> result = new(nodeData.Properties.Count);
            foreach (var prop in nodeData.Properties)
            {
                result.Add(new PropertyViewModel(prop.Key, prop.Value));
            }
            return result;
        }

        /// <summary>
        /// Obtain a command which manipulate target <see cref="NodeData"/> with the same TypeUID by infomation from UI.
        /// </summary>
        /// <param name="nodeData"> The data source with the same TypeUID. </param>
        /// <param name="propertyList"> 
        /// The <see cref="PropertyViewModel"/> generated by <see cref="GetPropertyViewModelOfNode"/>. 
        /// </param>
        /// <param name="context"> The <see cref="PropertyViewContext"/> of the node. </param>
        /// <param name="index"> Index of item in <see cref="PropertyViewModel"/>s. </param>
        /// <param name="edited"> The <see cref="string"/> as edit result. </param>
        /// <param name="subtype"></param>
        /// <returns></returns>
        protected virtual CommandBase ResolveCommandOfEditingNode(NodeData nodeData
            , IReadOnlyList<PropertyViewModel> propertyList, PropertyViewContext context
            , int index, string edited, int subtype = 0)
        {
            return EditPropertyCommand.CreateEditCommandOnDemand(nodeData, propertyList[index].Name, edited);
        }
    }
}
