<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>

    <BuildProjectReferences>false</BuildProjectReferences>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <OutputPath>$(MSBuildProjectDirectory)..\..\..\..\..\bin\$(Configuration)\package\LinqSTG\</OutputPath>

    <DisableTransitiveProjectReferences>true</DisableTransitiveProjectReferences>
    <InReferenceParent>true</InReferenceParent>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="images\relationships.png" />
    <None Remove="images\relationship_report.png" />
    <None Remove="images\shooter.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="images\relationships.png" />
    <Resource Include="images\relationship_report.png" />
    <Resource Include="images\shooter.png" />
  </ItemGroup>

</Project>
