//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuaSTGEditorSharpV2.Package.LinqSTG.Windows.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localized {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localized() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LuaSTGEditorSharpV2.Package.LinqSTG.Windows.Resources.Localized", typeof(Localized).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_intervalEditor_headClosed 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_intervalEditor_headClosed {
            get {
                return ResourceManager.GetString("linqstg_window_intervalEditor_headClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_intervalEditor_tailClosed 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_intervalEditor_tailClosed {
            get {
                return ResourceManager.GetString("linqstg_window_intervalEditor_tailClosed", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_label_end 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_label_end {
            get {
                return ResourceManager.GetString("linqstg_window_label_end", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_label_start 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_label_start {
            get {
                return ResourceManager.GetString("linqstg_window_label_start", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_label_time 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_label_time {
            get {
                return ResourceManager.GetString("linqstg_window_label_time", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 Search nodes 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_menu_searchHint {
            get {
                return ResourceManager.GetString("linqstg_window_menu_searchHint", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 No matching nodes 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_menu_noMatch {
            get {
                return ResourceManager.GetString("linqstg_window_menu_noMatch", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Data 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_menu_category_data {
            get {
                return ResourceManager.GetString("linqstg_window_menu_category_data", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Movement 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_menu_category_movement {
            get {
                return ResourceManager.GetString("linqstg_window_menu_category_movement", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Movement Operator 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_menu_category_movementoperator {
            get {
                return ResourceManager.GetString("linqstg_window_menu_category_movementoperator", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Movement Transform 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_menu_category_movementtransform {
            get {
                return ResourceManager.GetString("linqstg_window_menu_category_movementtransform", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Operator 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_menu_category_operator {
            get {
                return ResourceManager.GetString("linqstg_window_menu_category_operator", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Conversion 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_menu_category_operator_conversion {
            get {
                return ResourceManager.GetString("linqstg_window_menu_category_operator_conversion", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Context 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_menu_category_operator_context {
            get {
                return ResourceManager.GetString("linqstg_window_menu_category_operator_context", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Math 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_menu_category_operator_math {
            get {
                return ResourceManager.GetString("linqstg_window_menu_category_operator_math", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Pattern 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_menu_category_pattern {
            get {
                return ResourceManager.GetString("linqstg_window_menu_category_pattern", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Pattern Operator 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_menu_category_patternoperator {
            get {
                return ResourceManager.GetString("linqstg_window_menu_category_patternoperator", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Transformation 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_menu_category_transformation {
            get {
                return ResourceManager.GetString("linqstg_window_menu_category_transformation", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Shoot 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_menu_category_shoot {
            get {
                return ResourceManager.GetString("linqstg_window_menu_category_shoot", resourceCulture);
            }
        }
        /// <summary>
        ///   查找类似 Vector2 From Rotation Distance 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_vector2FromRotationDistance {
            get {
                return ResourceManager.GetString("linqstg_window_node_vector2FromRotationDistance", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_assign 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_assign {
            get {
                return ResourceManager.GetString("linqstg_window_node_assign", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_concatPattern 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_concatPattern {
            get {
                return ResourceManager.GetString("linqstg_window_node_concatPattern", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_emptyPattern 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_emptyPattern {
            get {
                return ResourceManager.GetString("linqstg_window_node_emptyPattern", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_extrudeConcatPattern 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_extrudeConcatPattern {
            get {
                return ResourceManager.GetString("linqstg_window_node_extrudeConcatPattern", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_extrudePattern 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_extrudePattern {
            get {
                return ResourceManager.GetString("linqstg_window_node_extrudePattern", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_filterPattern 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_filterPattern {
            get {
                return ResourceManager.GetString("linqstg_window_node_filterPattern", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_float 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_float {
            get {
                return ResourceManager.GetString("linqstg_window_node_float", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_floatToInt 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_floatToInt {
            get {
                return ResourceManager.GetString("linqstg_window_node_floatToInt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_int 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_int {
            get {
                return ResourceManager.GetString("linqstg_window_node_int", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_intToFloat 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_intToFloat {
            get {
                return ResourceManager.GetString("linqstg_window_node_intToFloat", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_mapPattern 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_mapPattern {
            get {
                return ResourceManager.GetString("linqstg_window_node_mapPattern", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_minMax 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_minMax {
            get {
                return ResourceManager.GetString("linqstg_window_node_minMax", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_movementAfterTime 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_movementAfterTime {
            get {
                return ResourceManager.GetString("linqstg_window_node_movementAfterTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_movementCartesianToPolar 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_movementCartesianToPolar {
            get {
                return ResourceManager.GetString("linqstg_window_node_movementCartesianToPolar", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_movementOffset 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_movementOffset {
            get {
                return ResourceManager.GetString("linqstg_window_node_movementOffset", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_movementPolarToCartesian 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_movementPolarToCartesian {
            get {
                return ResourceManager.GetString("linqstg_window_node_movementPolarToCartesian", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_movementRotate 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_movementRotate {
            get {
                return ResourceManager.GetString("linqstg_window_node_movementRotate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_movementScale 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_movementScale {
            get {
                return ResourceManager.GetString("linqstg_window_node_movementScale", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_movementSum 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_movementSum {
            get {
                return ResourceManager.GetString("linqstg_window_node_movementSum", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_repeatPattern 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_repeatPattern {
            get {
                return ResourceManager.GetString("linqstg_window_node_repeatPattern", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_repeatWithIntervalPattern 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_repeatWithIntervalPattern {
            get {
                return ResourceManager.GetString("linqstg_window_node_repeatWithIntervalPattern", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_repeaterKey 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_repeaterKey {
            get {
                return ResourceManager.GetString("linqstg_window_node_repeaterKey", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_reversePattern 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_reversePattern {
            get {
                return ResourceManager.GetString("linqstg_window_node_reversePattern", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_sample01MinMax 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_sample01MinMax {
            get {
                return ResourceManager.GetString("linqstg_window_node_sample01MinMax", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_shoot 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_shoot {
            get {
                return ResourceManager.GetString("linqstg_window_node_shoot", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_singleIntervalPattern 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_singleIntervalPattern {
            get {
                return ResourceManager.GetString("linqstg_window_node_singleIntervalPattern", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_singlePattern 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_singlePattern {
            get {
                return ResourceManager.GetString("linqstg_window_node_singlePattern", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_skipPattern 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_skipPattern {
            get {
                return ResourceManager.GetString("linqstg_window_node_skipPattern", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_skipWhilePattern 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_skipWhilePattern {
            get {
                return ResourceManager.GetString("linqstg_window_node_skipWhilePattern", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_fromPointMovement 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_fromPointMovement {
            get {
                return ResourceManager.GetString("linqstg_window_node_fromPointMovement", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_string 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_string {
            get {
                return ResourceManager.GetString("linqstg_window_node_string", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_takePattern 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_takePattern {
            get {
                return ResourceManager.GetString("linqstg_window_node_takePattern", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_takeRepeaterFromContext 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_takeRepeaterFromContext {
            get {
                return ResourceManager.GetString("linqstg_window_node_takeRepeaterFromContext", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_takeVariable 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_takeVariable {
            get {
                return ResourceManager.GetString("linqstg_window_node_takeVariable", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_takeWhilePattern 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_takeWhilePattern {
            get {
                return ResourceManager.GetString("linqstg_window_node_takeWhilePattern", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_transformInputTime 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_transformInputTime {
            get {
                return ResourceManager.GetString("linqstg_window_node_transformInputTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_variableFloat 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_variableFloat {
            get {
                return ResourceManager.GetString("linqstg_window_node_variableFloat", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_variableInt 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_variableInt {
            get {
                return ResourceManager.GetString("linqstg_window_node_variableInt", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_movementPredict 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_movementPredict {
            get {
                return ResourceManager.GetString("linqstg_window_node_movementPredict", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_movementScaleTime 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_movementScaleTime {
            get {
                return ResourceManager.GetString("linqstg_window_node_movementScaleTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_movementShiftTime 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_movementShiftTime {
            get {
                return ResourceManager.GetString("linqstg_window_node_movementShiftTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_trim 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_trim {
            get {
                return ResourceManager.GetString("linqstg_window_node_trim", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_trimEnd 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_trimEnd {
            get {
                return ResourceManager.GetString("linqstg_window_node_trimEnd", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_trimStart 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_trimStart {
            get {
                return ResourceManager.GetString("linqstg_window_node_trimStart", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_uniformAccelerationMovement 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_uniformAccelerationMovement {
            get {
                return ResourceManager.GetString("linqstg_window_node_uniformAccelerationMovement", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_uniformVelocityMovement 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_uniformVelocityMovement {
            get {
                return ResourceManager.GetString("linqstg_window_node_uniformVelocityMovement", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_vector2 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_vector2 {
            get {
                return ResourceManager.GetString("linqstg_window_node_vector2", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_vector2Split 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_vector2Split {
            get {
                return ResourceManager.GetString("linqstg_window_node_vector2Split", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_node_rotateVector 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_node_rotateVector {
            get {
                return ResourceManager.GetString("linqstg_window_node_rotateVector", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_acceleration 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_acceleration {
            get {
                return ResourceManager.GetString("linqstg_window_port_acceleration", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_after 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_after {
            get {
                return ResourceManager.GetString("linqstg_window_port_after", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_angle 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_angle {
            get {
                return ResourceManager.GetString("linqstg_window_port_angle", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_base 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_base {
            get {
                return ResourceManager.GetString("linqstg_window_port_base", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_center 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_center {
            get {
                return ResourceManager.GetString("linqstg_window_port_center", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_count 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_count {
            get {
                return ResourceManager.GetString("linqstg_window_port_count", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_diameter 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_diameter {
            get {
                return ResourceManager.GetString("linqstg_window_port_diameter", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_distance 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_distance {
            get {
                return ResourceManager.GetString("linqstg_window_port_distance", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_exponent 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_exponent {
            get {
                return ResourceManager.GetString("linqstg_window_port_exponent", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_float 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_float {
            get {
                return ResourceManager.GetString("linqstg_window_port_float", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_idKey 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_idKey {
            get {
                return ResourceManager.GetString("linqstg_window_port_idKey", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_initialVelocity 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_initialVelocity {
            get {
                return ResourceManager.GetString("linqstg_window_port_initialVelocity", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_int 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_int {
            get {
                return ResourceManager.GetString("linqstg_window_port_int", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_interval 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_interval {
            get {
                return ResourceManager.GetString("linqstg_window_port_interval", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_key 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_key {
            get {
                return ResourceManager.GetString("linqstg_window_port_key", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_lowerBound 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_lowerBound {
            get {
                return ResourceManager.GetString("linqstg_window_port_lowerBound", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_movement 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_movement {
            get {
                return ResourceManager.GetString("linqstg_window_port_movement", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_offset 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_offset {
            get {
                return ResourceManager.GetString("linqstg_window_port_offset", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_pattern 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_pattern {
            get {
                return ResourceManager.GetString("linqstg_window_port_pattern", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_pattern1 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_pattern1 {
            get {
                return ResourceManager.GetString("linqstg_window_port_pattern1", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_pattern2 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_pattern2 {
            get {
                return ResourceManager.GetString("linqstg_window_port_pattern2", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_point 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_point {
            get {
                return ResourceManager.GetString("linqstg_window_port_point", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_time 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_time {
            get {
                return ResourceManager.GetString("linqstg_window_port_time", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_factor 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_factor {
            get {
                return ResourceManager.GetString("linqstg_window_port_factor", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_delta 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_delta {
            get {
                return ResourceManager.GetString("linqstg_window_port_delta", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_position 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_position {
            get {
                return ResourceManager.GetString("linqstg_window_port_position", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_predicate 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_predicate {
            get {
                return ResourceManager.GetString("linqstg_window_port_predicate", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_repeater 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_repeater {
            get {
                return ResourceManager.GetString("linqstg_window_port_repeater", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_repeaterKey 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_repeaterKey {
            get {
                return ResourceManager.GetString("linqstg_window_port_repeaterKey", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_rotation 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_rotation {
            get {
                return ResourceManager.GetString("linqstg_window_port_rotation", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_sampleMethod 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_sampleMethod {
            get {
                return ResourceManager.GetString("linqstg_window_port_sampleMethod", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_scale 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_scale {
            get {
                return ResourceManager.GetString("linqstg_window_port_scale", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_shape 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_shape {
            get {
                return ResourceManager.GetString("linqstg_window_port_shape", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_shooterName 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_shooterName {
            get {
                return ResourceManager.GetString("linqstg_window_port_shooterName", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_subPattern 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_subPattern {
            get {
                return ResourceManager.GetString("linqstg_window_port_subPattern", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_switchTime 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_switchTime {
            get {
                return ResourceManager.GetString("linqstg_window_port_switchTime", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_times 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_times {
            get {
                return ResourceManager.GetString("linqstg_window_port_times", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_totalKey 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_totalKey {
            get {
                return ResourceManager.GetString("linqstg_window_port_totalKey", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_transformation 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_transformation {
            get {
                return ResourceManager.GetString("linqstg_window_port_transformation", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_upperBound 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_upperBound {
            get {
                return ResourceManager.GetString("linqstg_window_port_upperBound", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_value 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_value {
            get {
                return ResourceManager.GetString("linqstg_window_port_value", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_vector2 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_vector2 {
            get {
                return ResourceManager.GetString("linqstg_window_port_vector2", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_port_velocity 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_port_velocity {
            get {
                return ResourceManager.GetString("linqstg_window_port_velocity", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_title 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_title {
            get {
                return ResourceManager.GetString("linqstg_window_title", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_varList_add 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_varList_add {
            get {
                return ResourceManager.GetString("linqstg_window_varList_add", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_varList_drag 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_varList_drag {
            get {
                return ResourceManager.GetString("linqstg_window_varList_drag", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_varList_remove 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_varList_remove {
            get {
                return ResourceManager.GetString("linqstg_window_varList_remove", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 linqstg_window_varList_title 的本地化字符串。
        /// </summary>
        internal static string linqstg_window_varList_title {
            get {
                return ResourceManager.GetString("linqstg_window_varList_title", resourceCulture);
            }
        }
    }
}
